# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Table_UI(object):
    listOfUser = list()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(526, 519)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(50, 10, 421, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        number_rows = len(Table_UI.listOfUser)
        self.tableWidget.setRowCount(number_rows)
        for value in range(0, number_rows):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setVerticalHeaderItem(value, item)

        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        for i in range(0, number_rows):
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 0, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 1, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 2, item)
            item = QtWidgets.QTableWidgetItem()
            self.tableWidget.setItem(i, 3, item)
        # TRANSLATE

        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        for value in range(0, number_rows):
            item = self.tableWidget.verticalHeaderItem(value)
            item.setText(_translate("Form", str(value)))

        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Prenom"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nom"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Role"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        for number, value in enumerate(Table_UI.listOfUser):
            role = ','.join(value[4:])
            self.tableWidget.setSortingEnabled(False)
            item = self.tableWidget.item(number, 0)
            item.setText(_translate("Form", value[1]))
            item = self.tableWidget.item(number, 1)
            item.setText(_translate("Form", value[2]))
            item = self.tableWidget.item(number, 2)
            item.setText(_translate("Form", value[3]))
            item = self.tableWidget.item(number, 3)
            item.setText(_translate("Form", role))
            self.tableWidget.setSortingEnabled(__sortingEnabled)

        QtCore.QMetaObject.connectSlotsByName(Form)
